// 화면 공통 스타일 토큰 (가져오기/대시보드/복습 화면에서 재사용)

export const colors = {
  primary: '#4f46e5',
  primaryDark: '#3730a3',
  bg: '#f5f5ff',
  text: '#333',
  textMuted: '#888',
  green: '#16a34a',
  greenBg: '#f0fdf4',
  greenBorder: '#86efac',
  red: '#dc2626',
  redBg: '#fff0f0',
  redBorder: '#fca5a5',
  amber: '#92400e',
  amberBg: '#fffbeb',
  amberBorder: '#fcd34d',
}

export const styles = {
  page: {
    minHeight: '100vh',
    background: colors.bg,
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    padding: '1.5rem 1rem',
    boxSizing: 'border-box' as const,
  },
  card: {
    background: 'white',
    borderRadius: '1.25rem',
    padding: '1.5rem',
    boxShadow: '0 4px 20px rgba(79,70,229,0.1)',
    width: '100%',
    maxWidth: '480px',
    height: 'fit-content',
    boxSizing: 'border-box' as const,
  },
  title: {
    fontSize: '1.25rem',
    fontWeight: 700,
    color: colors.primary,
    margin: '0 0 0.25rem',
  },
  sectionTitle: {
    fontSize: '1.1rem',
    fontWeight: 700,
    color: colors.primary,
    margin: '0 0 0.25rem',
  },
  subtitle: {
    fontSize: '0.875rem',
    color: colors.textMuted,
    margin: '0 0 1rem',
  },
  button: {
    marginTop: '0.75rem',
    width: '100%',
    padding: '0.875rem',
    background: colors.primary,
    color: 'white',
    border: 'none',
    borderRadius: '0.75rem',
    fontSize: '1rem',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'opacity 0.15s',
  },
  secondaryButton: {
    marginTop: '0.75rem',
    width: '100%',
    padding: '0.875rem',
    background: 'white',
    color: colors.primary,
    border: `1.5px solid ${colors.primary}`,
    borderRadius: '0.75rem',
    fontSize: '1rem',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'opacity 0.15s',
  },
  errorBox: {
    marginTop: '1rem',
    background: colors.redBg,
    border: `1px solid ${colors.redBorder}`,
    borderRadius: '0.75rem',
    padding: '0.875rem',
  },
  errorTitle: {
    fontWeight: 700,
    color: colors.red,
    margin: '0 0 0.5rem',
    fontSize: '0.95rem',
  },
  errorMsg: {
    color: colors.red,
    fontSize: '0.85rem',
    margin: '0.25rem 0 0',
    lineHeight: 1.5,
  },
  resultBox: {
    marginTop: '1rem',
    background: colors.greenBg,
    border: `1px solid ${colors.greenBorder}`,
    borderRadius: '0.75rem',
    padding: '0.875rem',
  },
  resultTitle: {
    fontWeight: 700,
    color: colors.green,
    margin: '0 0 0.75rem',
    fontSize: '0.95rem',
  },
  counts: {
    display: 'flex',
    gap: '0.5rem',
    flexWrap: 'wrap' as const,
  },
  badge: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    background: 'white',
    border: `1px solid ${colors.greenBorder}`,
    borderRadius: '0.5rem',
    padding: '0.4rem 0.75rem',
    minWidth: '3.5rem',
  },
  badgeNum: {
    fontSize: '1.25rem',
    fontWeight: 700,
    color: colors.green,
    lineHeight: 1,
  },
  badgeLabel: {
    fontSize: '0.7rem',
    color: '#666',
    marginTop: '0.2rem',
  },
  warnBox: {
    marginTop: '0.75rem',
    background: colors.amberBg,
    border: `1px solid ${colors.amberBorder}`,
    borderRadius: '0.5rem',
    padding: '0.75rem',
  },
  warnTitle: {
    fontWeight: 600,
    color: colors.amber,
    margin: '0 0 0.5rem',
    fontSize: '0.85rem',
  },
  warnMsg: {
    color: '#78350f',
    fontSize: '0.8rem',
    margin: '0.2rem 0 0',
    lineHeight: 1.5,
  },
  divider: {
    height: '1px',
    background: '#eee',
    margin: '1rem 0',
  },
} as const
